name: Test Memory Error Windows Server

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        first: [ 'ffi', 'standalone' ]

    name: ${{ matrix.first }} first

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: openssl, sockets, curl, zip, ffi
          php-version: 8.2

      - name: Composer install
        uses: ramsey/composer-install@v2

      - name: Composer test
        run: composer ${{ matrix.first }}-first
